name: hsas

channels:
  - pytorch
  - conda-forge

dependencies:
  - pip=21.2.4
  - python=3.9.6
  - cudatoolkit=10.2.89
  - pytorch=1.10.0
  - torchaudio=0.10.0
  - pandas=1.3.3
  - tqdm=4.62.3
  - numpy=1.22.1
  - transformers=4.11.3

  - pip:
    - sacrebleu==1.5.0
    - sacremoses==0.0.46
    - webrtcvad==2.0.10
    - pydub==0.25.1
    - wandb==0.12.9
    - SoundFile==0.10.3.post1
    - PyYAML==6.0
    - scikit_learn==1.0.2
    - tweepy==4.5.0
    - sentencepiece==0.1.96